apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beard-api
  labels:
    commit: ${WERCKER_GIT_COMMIT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beard-api
  template:
    metadata:
      labels:
        app: beard-api
        commit: ${WERCKER_GIT_COMMIT}
    spec:
      containers:
      - name: beard-api
        image: wcr.io/${WERCKER_APPLICATION_OWNER_NAME}/beard-api:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        imagePullPolicy: Always
        volumeMounts:
        - name: beard-tweet-storage
          mountPath: /tweet
        ports:
        - name: beard-api
          containerPort: 5000
          protocol: TCP
      imagePullSecrets:
        - name: wercker
      volumes:
        - name: beard-tweet-storage
          persistentVolumeClaim:
            claimName: beard-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: beard-api
  labels:
    app: beard-api
    commit: ${WERCKER_GIT_COMMIT}
spec:
  ports:
  - port: 30000
    targetPort: 5000
  selector:
    app: beard-api
    commit: ${WERCKER_GIT_COMMIT}
# commented out following line, as Load balancers are in short supply.
# Instead can access service endpoints using proxy mechanism.
#  type: LoadBalancer
---